language: generic
sudo: required
before_script:
- curl -L https://github.com/opctl/opctl/releases/download/0.1.22/opctl0.1.22.linux.tgz | sudo tar -xzv -C /usr/local/bin
services:
- docker
script:
- opctl run build
